python -u main.py --anormly_ratio 1 \
                    --num_epochs 10   \
                    --cluster_temporal 30 \
                    --cluster_channel 4 \
                    --batch_size 16  \
                    --mode train \
                    --dataset SMAP  \
                    --data_path /path/to/dataset/ \
                    --input_c 25    \
                    --output_c 25
python -u main.py --anormly_ratio 1  \
                    --num_epochs 10        \
                    --cluster_temporal 30 \
                    --cluster_channel 4 \
                    --batch_size 16     \
                    --mode test    \
                    --dataset SMAP   \
                    --data_path /path/to/dataset/  \
                    --input_c 25    \
                    --output_c 25  \
                    --pretrained_model 20
